FROM node:20-alpine

WORKDIR /app

COPY . .
RUN npm install

COPY . .

ARG NEXT_PUBLIC_SERVER_URL
ARG NEXT_PUBLIC_BASE_URL
ARG NEXT_PUBLIC_CYPHER_KEY

ENV NEXT_PUBLIC_SERVER_URL=$NEXT_PUBLIC_SERVER_URL
ENV NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL
ENV NEXT_PUBLIC_CYPHER_KEY=$NEXT_PUBLIC_CYPHER_KEY

RUN npm run build

EXPOSE 3001
CMD ["npm","start","--","-p","3001"]
