import CustomButton from "@/Components/UI/Buttons";
import useIsMobile from "@/hooks/useIsMobile";
import { pageProps } from "@/utils/types";
import { AddRounded } from "@mui/icons-material";
import Head from "next/head";
import router from "next/router";
import { useEffect, useCallback } from "react";
import { useTranslation } from "react-i18next";
import { Box, Grid } from "@mui/material";
import DashboardLeftSection from "@/Components/Page/Dashboard/DashboardLeftSection";
import DashboardRightSection from "@/Components/Page/Dashboard/DashboardRightSection";

export default function Home({
  setPageName,
  setPageDescription,
  setPageAction,
}: pageProps) {
  const namespaces = ["dashboardLayout", "common"];

  const isMobile = useIsMobile("md");
  const { t } = useTranslation(namespaces);
  const tDashboard = useCallback(
    (key: string) => t(key, { ns: "dashboardLayout" }),
    [t]
  );
  const tCommon = useCallback((key: string) => t(key, { ns: "common" }), [t]);

  useEffect(() => {
    if (setPageName && setPageDescription) {
      // Using dashboardLayout namespace
      setPageName(tDashboard("dashboard"));
      setPageDescription(tDashboard("dashboardDescription"));
    }
  }, [setPageName, setPageDescription, tDashboard]);

  useEffect(() => {
    if (!setPageAction) return;
    setPageAction(
      <CustomButton
        label={
          isMobile
            ? tDashboard("create")
            : tDashboard("createPaymentLink")
        }
        variant="primary"
        size="medium"
        endIcon={<AddRounded sx={{ fontSize: isMobile ? 18 : 20 }} />}
        onClick={() => router.push("/create-pay-link")}
        sx={{
          height: isMobile ? 34 : 40,
          px: isMobile ? 1.5 : 2.5,
          fontSize: isMobile ? 13 : 15,
        }}
      />
    );
    return () => setPageAction(null);
  }, [setPageAction, tDashboard, isMobile]);

  return (
    <>
      <Head>
        <title>BozzWallet</title>
        <meta name="description" content="Generated by next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main>
        <Grid container spacing={2.5}>
          {/* Left Section - Stat Cards and Graph */}
          <Grid item xs={12} lg={8}>
            <DashboardLeftSection />
          </Grid>

          {/* Right Section - Fee Tier and Upgrade */}
          <Grid item xs={12} lg={4}>
            <DashboardRightSection />
          </Grid>
        </Grid>
      </main>
    </>
  );
}
